type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  bio: String
  profilePictureUrl: String
}

type Story @table {
  user: User!
  videoUrl: String!
  createdAt: Timestamp!
  expiresAt: Timestamp!
  caption: String
  filterApplied: String
}

type Follow @table(key: ["follower", "followed"]) {
  follower: User!
  followed: User!
  createdAt: Timestamp!
}

type Reaction @table(key: ["user", "story"]) {
  user: User!
  story: Story!
  emoji: String!
  createdAt: Timestamp!
}

type Message @table {
  sender: User!
  receiver: User!
  content: String!
  createdAt: Timestamp!
  inReplyToStory: Story
}